### ISSUE TITLE
[Bug]: Teal app crashes when the input teal_data has objects that fail `check_simple_name()`

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/teal#1366] opened 2024-10-08 12:34 UTC
### What happened?

Please use the `main` branch version of packages.

This issue started after we [made the change](https://github.com/insightsengineering/teal/pull/1334) to pass all the objects from the `teal_data` in certain scenarios.
The actual error happens in `teal.slice` where [all the object names are recieved](https://github.com/insightsengineering/teal.slice/blob/aa05f7feb26bb32fbb5f069ec3e9e77d17450022/R/FilteredData.R#L130). This R6 class object is initialized in `teal` using the helper function `teal_data_to_filtered_data, by [default this takes the datanames as a list of all the objects in the `teal_data` object.](https://github.com/insightsengineering/teal/blob/e6db5cafbab56d8ac9c4dd55b2c1200f00e7a968/R/utils.R#L77)

Example app to test:

```r
devtools::load_all("teal")

data <- teal_data() |>
  within({
    IRIS <- iris
    MTCARS <- mtcars
    `%keep_label%` <- function(lhv, rhv) {
      attributes(lhv) <- attributes(rhv)
      lhv
    }
  })

datanames(data) <- c("IRIS", "MTCARS")

init(
  data = data,
  modules <- modules(
    example_module()
  )
) |>
  runApp()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment] 2024-10-08 13:44
The core of the issue is that names of the object in `teal_data` might contain objects which are not accepted by `teal.slice`. You can specify `%make_label%` as a dataname and it will fail as well. I would change the function name to `.make_label` if it is needed only in the preprocessing, or synchronise allowed datanames in teal.data with allowed datanames in teal.slice. I think `teal.slice` should accept any syntactically valid name (see `?make.names`).

**Comment by gogonzo** [comment] 2024-10-15 06:13
@vedhav can we close this?

**Comment by gogonzo** [comment] 2024-10-15 07:11
`teal.gallery` apps have been fixed but error can occur anytime when somebody passes some exotic datanames which can't be just typed in the console without backticks. We should open filter panel to accept those.

**Closed** 2024-10-22 12:50 UTC
Labels: bug, core
