### ISSUE TITLE
sessionInfo() improvement

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal#775] opened 2022-11-14 09:28 UTC
Comment from @Polkas in https://github.com/insightsengineering/teal/issues/752#issuecomment-1305409874: 
```
In my opinion already done part about session info could be improved with sessioninfo::session_info() or the renv lock file. 
 
Mostly nobody want to see the sessionInfo but to quickly reproduce the env so renv lock file could be the right direction.
@nikolas-burkoff what you think?
```

**Comment by gogonzo** [comment] 2022-11-15 10:30
duplicate of https://github.com/insightsengineering/teal/issues/614

**Closed by gogonzo** 2022-11-15 10:30 UTC
Labels: core
